2023-02-22 05:10:49,993 - DEBUG - This is a debug message
2023-02-22 05:10:49,993 - INFO - This is an info message
2023-02-22 05:10:49,993 - WARNING - This is a warning message
2023-02-22 05:10:49,993 - ERROR - This is an error message
2023-02-22 05:10:49,994 - CRITICAL - This is a critical message
2023-02-22 05:11:58,016 - DEBUG - This is a debug message
2023-02-22 05:11:58,017 - INFO - This is an info message
2023-02-22 05:11:58,017 - WARNING - This is a warning message
2023-02-22 05:11:58,017 - ERROR - This is an error message
2023-02-22 05:11:58,017 - CRITICAL - This is a critical message
2023-02-22 05:11:58,017 - ERROR - An error occurred: division by zero
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    1/0
ZeroDivisionError: division by zero
2023-02-22 21:01:22,978 - DEBUG - This is a debug message
2023-02-22 21:01:22,979 - INFO - This is an info message
2023-02-22 21:01:22,979 - WARNING - This is a warning message
2023-02-22 21:01:22,979 - ERROR - This is an error message
2023-02-22 21:01:22,979 - CRITICAL - This is a critical message
2023-02-22 21:01:22,979 - ERROR - An error occurred: division by zero
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    1/0
ZeroDivisionError: division by zero
2023-02-22 21:01:45,203 - DEBUG - This is a debug message
2023-02-22 21:01:45,204 - INFO - This is an info message
2023-02-22 21:01:45,204 - WARNING - This is a warning message
2023-02-22 21:01:45,204 - ERROR - This is an error message
2023-02-22 21:01:45,204 - CRITICAL - This is a critical message
2023-02-22 21:01:45,204 - ERROR - An error occurred: division by zero
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    1/0
ZeroDivisionError: division by zero
